name: Add JIRA Link to PR
on:
  pull_request:
    types: [opened]

jobs:
  add-jira-link:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Add JIRA Link Comment
        uses: actions/github-script@v7
        with:
          script: |
            // Extract JIRA issue ID from branch name
            const branchName = context.payload.pull_request.head.ref;
            const jiraMatch = branchName.match(/[A-Z]+-\d+/);
            
            if (jiraMatch) {
              const jiraId = jiraMatch[0];
              const jiraLink = `https://archipro.atlassian.net/browse/${jiraId}`;
              
              // Create comment with JIRA link
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `📎 Related JIRA Issue: [${jiraId}](${jiraLink})`
              });
            }